### ISSUE TITLE
Country selection

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Design#1]
What is the purpose of country selection? The base user role, the Buyer, will need to add their shipping address at some point, can't we pull the country from there?

**Comment by morebrownies** [comment]
It's for optimizing the first time experience. The application could connect you to nodes in your region immediately after on-boarding, instead of connecting you with nodes across the globe.

**Comment by gubatron** [comment]
I'd say also to autoselect the default display fiat currency to that user.
Every user should always see prices in the currency of their preference (regardless of the store they connect to) so that they can easily judge the worth of the items they intend to purchase.
(in the end it all will flow in bitcoin, but people don't even need to know about the bitcoin amount until it's time for paying, or unless they're curious, IMO, keep it friendly and familiar to what they know)

**Comment by morebrownies** [comment]
I agree @gubatron. A user should always see the bitcoin price and their local currency price. 

Example: $34 (0.13 btc)

**Comment by drwasho** [comment]
Cool.
